language: csharp
solution: unit-testing-using-dotnet-test.sln

group: travis_latest

dotnet: 5.0
mono: none

env:
  global:
    - CONFIGURATION: Release
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - NET_CORE_VERSION: netcoreapp5.0
    
script:
 - dotnet restore
 - dotnet build
 - dotnet test